name: jee_challenge
description: 180 Days JEE 2027 Challenge Tracker

version: 1.1.0+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
